import customtkinter as ctk
app = ctk.CTk()
ctk.CTkLabel(app, text="Anonymous", text_color=("red", "blue")).pack()
l = ctk.CTkLabel(app, text="Saved", text_color=("red", "blue"))
l.pack()
app.update()
import gc; gc.collect()
ctk.set_appearance_mode("dark")
app.update()
app.after(100, app.destroy)
app.mainloop()
